"""empty message

Revision ID: ac2b74d61dc6
Revises: 
Create Date: 2019-11-20 11:28:59.630782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2b74d61dc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('accountNo', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.String(length=20), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('citizenID', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accountNo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_historys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=10), nullable=True),
    sa.Column('to_account', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.String(length=10), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_historys')
    op.drop_table('login_logs')
    op.drop_table('users')
    op.drop_table('token_counts')
    # ### end Alembic commands ###
